update ci

diff --git a/.github/workflows/buildtest.yml b/.github/workflows/buildtest.yml
--- a/.github/workflows/buildtest.yml
+++ b/.github/workflows/buildtest.yml
@@ -118,9 +118,9 @@ jobs:
       - name: Check debug makeflags
         if: matrix.config.buildType == 'Debug'
         run: |
-          docker exec ci bash -c " grep  -e \"-g\"  /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep  -e \"-O3\" /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; test $? -eq 1 || (echo \"Error: Unexpected flag \'-O3\' for debug build.\" && false)"
-          docker exec ci bash -c " grep  -e \"-DNDEBUG\" /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; test $? -eq 1  || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c "if ! grep -q e '-g' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Missing flag '-g' for debug build.\"; exit 1; fi"
+          docker exec ci bash -c "if grep -q e '-O3' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-O3' for debug build.\"; exit 1; fi"
+          docker exec ci bash -c "if grep -q e '-DNDEBUG' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-DNDEBUG' for debug build.\"; exit 1; fi"
 
       - name: Build tests
         run: docker exec ci bash -c "cd /opt/storm/build; make -j ${NR_JOBS}"
@@ -180,15 +180,15 @@ jobs:
       - name: Check release makeflags
         if: matrix.config.buildType == 'Release'
         run: |
-          docker exec ci bash -c " grep -e -g /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; test $? -eq 1  || (echo \"Error: Unexpected flag \'-g\' for release build.\" && false)"
-          docker exec ci bash -c " grep -e -O3 /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make  || (echo \"Error: Missing flag \'-O3\' for release build.\" && false)"
-          docker exec ci bash -c " grep -e -DNDEBUG /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make || (echo \"Error: Missing flag \'-DNDEBUG\' for release build.\" && false)"
+          docker exec ci bash -c "if grep -q e '-g' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-g' for release build.\"; exit 1; fi"
+          docker exec ci bash -c "if ! grep -q e '-O3' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Missing flag '-O3' for release build.\"; exit 1; fi"
+          docker exec ci bash -c "if ! grep -q e '-DNDEBUG' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Missing flag '-DNDEBUG' for release build.\"; exit 1; fi"
       - name: Check debug makeflags
         if: matrix.config.buildType == 'Debug'
         run: |
-          docker exec ci bash -c " grep  -e -g /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep -e -O3 /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; test $? -eq 1  || (echo \"Error: Unexpected flag \'-O3\' for debug build.\" && false)"
-          docker exec ci bash -c " grep -e -DNDEBUG /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; test $? -eq 1  || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c "if ! grep -q e '-g' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Missing flag '-g' for debug build.\"; exit 1; fi"
+          docker exec ci bash -c "if grep -q e '-O3' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-O3' for debug build.\"; exit 1; fi"
+          docker exec ci bash -c "if grep -q e '-DNDEBUG' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-DNDEBUG' for debug build.\"; exit 1; fi"
 
       - name: Build tests
         run: docker exec ci bash -c "cd /opt/storm/build; make -j ${NR_JOBS}"
@@ -229,15 +229,15 @@ jobs:
       - name: Check release makeflags
         if: matrix.buildType == 'Release'
         run: |
-          docker exec ci bash -c " grep -e -g /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make ;  test $? -eq 1 || (echo \"Error: Unexpected flag \'-g\' for release build.\" && false)"
-          docker exec ci bash -c " grep -e -O3  /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make || (echo \"Error: Missing flag \'-O3\' for release build.\" && false)"
-          docker exec ci bash -c " grep -e -DNDEBUG  /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make  || (echo \"Error: Missing flag \'-DNDEBUG\' for release build.\" && false)"
+          docker exec ci bash -c "if grep -q e '-g' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-g' for release build.\"; exit 1; fi"
+          docker exec ci bash -c "if ! grep -q e '-O3' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Missing flag '-O3' for release build.\"; exit 1; fi"
+          docker exec ci bash -c "if ! grep -q e '-DNDEBUG' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Missing flag '-DNDEBUG' for release build.\"; exit 1; fi"
       - name: Check debug makeflags
         if: matrix.buildType == 'Debug'
         run: |
-          docker exec ci bash -c " grep -e -g /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make  || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep -e -O3 /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make;  test $? -eq 1 || (echo \"Error: Unexpected flag \'-O3\' for debug build.\" && false)"
-          docker exec ci bash -c " grep -e -DNDEBUG /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make ; test $? -eq 1 || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c "if ! grep -q e '-g' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Missing flag '-g' for debug build.\"; exit 1; fi"
+          docker exec ci bash -c "if grep -q e '-O3' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-O3' for debug build.\"; exit 1; fi"
+          docker exec ci bash -c "if grep -q e '-DNDEBUG' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-DNDEBUG' for debug build.\"; exit 1; fi"
 
       - name: Build tests
         run: docker exec ci bash -c "cd /opt/storm/build; make -j ${NR_JOBS}"
@@ -298,15 +298,15 @@ jobs:
       - name: Check release makeflags
         if: matrix.buildType.name == 'Release'
         run: |
-          docker exec ci bash -c " grep -e -g /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; test $? -eq 1  || (echo \"Error: Unexpected flag \'-g\' for release build.\" && false)"
-          docker exec ci bash -c " grep -e -O3 /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make || (echo \"Error: Missing flag \'-O3\' for release build.\" && false)"
-          docker exec ci bash -c " grep -e -DNDEBUG /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make || (echo \"Error: Missing flag \'-DNDEBUG\' for release build.\" && false)"
+          docker exec ci bash -c "if grep -q e '-g' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-g' for release build.\"; exit 1; fi"
+          docker exec ci bash -c "if ! grep -q e '-O3' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Missing flag '-O3' for release build.\"; exit 1; fi"
+          docker exec ci bash -c "if ! grep -q e '-DNDEBUG' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Missing flag '-DNDEBUG' for release build.\"; exit 1; fi"
       - name: Check debug makeflags
         if: matrix.buildType.name == 'Debug'
         run: |
-          docker exec ci bash -c " grep -e -g /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep -e -O3 /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; test $? -eq 1  || (echo \"Error: Unexpected flag \'-O3\' for debug build.\" && false)"
-          docker exec ci bash -c " grep -e -DNDEBUG /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; test $? -eq 1  || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c "if ! grep -q e '-g' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Missing flag '-g' for debug build.\"; exit 1; fi"
+          docker exec ci bash -c "if grep -q e '-O3' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-O3' for debug build.\"; exit 1; fi"
+          docker exec ci bash -c "if grep -q e '-DNDEBUG' /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make; then echo \"Error: Unexpected flag '-DNDEBUG' for debug build.\"; exit 1; fi"
 
       - name: Build tests
         run: docker exec ci bash -c "cd /opt/storm/build; make -j ${NR_JOBS}"
