updates based on CI and z3 support for older versions

diff --git a/.github/workflows/buildtest.yml b/.github/workflows/buildtest.yml
--- a/.github/workflows/buildtest.yml
+++ b/.github/workflows/buildtest.yml
@@ -114,13 +114,13 @@ jobs:
         run: |
           docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-g" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
           docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-O3" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-DNDEBUG" || (echo \"Error: Missing flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-DNDEBUG" || (echo \"Error: Missing flag \'-DNDEBUG\' for debug build.\" && false)"
       - name: Check debug makeflags
         if: matrix.config.buildType == 'Debug'
         run: |
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-g" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-O3" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-DNDEBUG" || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-g" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-O3" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-DNDEBUG" || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
 
       - name: Build tests
         run: docker exec ci bash -c "cd /opt/storm/build; make -j ${NR_JOBS}"
@@ -180,15 +180,15 @@ jobs:
       - name: Check release makeflags
         if: matrix.config.buildType == 'Release'
         run: |
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-g" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-O3" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-DNDEBUG" || (echo \"Error: Missing flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-g" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-O3" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-DNDEBUG" || (echo \"Error: Missing flag \'-DNDEBUG\' for debug build.\" && false)"
       - name: Check debug makeflags
         if: matrix.config.buildType == 'Debug'
         run: |
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-g" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-O3" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-DNDEBUG" || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-g" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-O3" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-DNDEBUG" || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
 
       - name: Build tests
         run: docker exec ci bash -c "cd /opt/storm/build; make -j ${NR_JOBS}"
@@ -226,15 +226,15 @@ jobs:
       - name: Check release makeflags
         if: matrix.config.buildType == 'Release'
         run: |
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-g" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-O3" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-DNDEBUG" || (echo \"Error: Missing flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-g" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-O3" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-DNDEBUG" || (echo \"Error: Missing flag \'-DNDEBUG\' for debug build.\" && false)"
       - name: Check debug makeflags
         if: matrix.config.buildType == 'Debug'
         run: |
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-g" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-O3" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-DNDEBUG" || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-g" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-O3" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-DNDEBUG" || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
 
       - name: Build tests
         run: docker exec ci bash -c "cd /opt/storm/build; make -j ${NR_JOBS}"
@@ -284,15 +284,15 @@ jobs:
       - name: Check release makeflags
         if: matrix.config.buildType == 'Release'
         run: |
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-g" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-O3" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-DNDEBUG" || (echo \"Error: Missing flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-g" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-O3" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-DNDEBUG" || (echo \"Error: Missing flag \'-DNDEBUG\' for debug build.\" && false)"
       - name: Check debug makeflags
         if: matrix.config.buildType == 'Debug'
         run: |
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -e "-g" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-O3" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
-          docker exec ci bash -c " grep /opt/storm/buildsrc/storm/CMakeFiles/storm.dir/flags.make -ev "-DNDEBUG" || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -e "-g" || (echo \"Error: Missing flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-O3" || (echo \"Error: Unexpected flag \'-g\' for debug build.\" && false)"
+          docker exec ci bash -c " grep /opt/storm/build/src/storm/CMakeFiles/storm.dir/flags.make -ev "-DNDEBUG" || (echo \"Error: Unexpected flag \'-DNDEBUG\' for debug build.\" && false)"
 
       - name: Build tests
         run: docker exec ci bash -c "cd /opt/storm/build; make -j ${NR_JOBS}"
